# Dockerfile for general node-based API server

FROM node:10

LABEL version="1.0"
LABEL maintainer="Ryan Robillard github.com/rrobilla"
LABEL description="This is the Node server to serve the React client."

